#!/bin/bash

# HTTP Ping
# 2012/12/16	Denny

# Target web url or ip on first argument

end()
{
	echo -e "\n"
	echo $res |\
		sed 's/ /\n/g' |\
		sed '$d' |\
		awk '{res[$0]++; times++;} END {for(code in res) printf("%d/%d %d%% - %s\n", res[code], times, (res[code]/times)*100, code)}'
	exit 0
}

trap end SIGINT
echo -e "status code, namelookupg, connect, appconnect, pretransfer, redirect, starttransfer, total"
while [ 1 ]
do
	tmp=`curl -s -m 3 -o /dev/null -A 'Denny HTTP Ping v1.1' -w "%{http_code} %{time_namelookup}\t%{time_connect}\t%{time_appconnect}\t%{time_pretransfer}\t%{time_redirect}\t%{time_starttransfer}\t%{time_total}\n" $1`
	echo $tmp
	res=$res' '$(echo $tmp | awk '{print $1}')
	sleep 1
done

